[lib]

[package]
name = "macro_basic"
version = "0.1.0"
edition = "2021"

[dependencies]
quote = "1.0.28"
syn = "2.0.22"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
